
public enum TagType : byte
{
	None = 0,
	Player = 1,
	EnemyPart = 2,
	Wall = 3,
	Web = 4,
	MovingPoint = 5,
	Object = 6,
	SimpleEnemy = 7,
	ThrowingEnemy =8,
	Buildings1 = 9,
	Buildings2 = 10,
	BuildingCube = 11,
	Bottom = 12,
	BossSet = 13,
	JokerMask = 14,
	MisterioMask = 15,
	GoblinMask = 16,
	ShieldEnemy = 17,
	BankBuilding = 18,
	Buildings3 = 19,
	Buildings4 = 20,
	RoofBuilding = 21,
	BuildingConstr1 = 22,
	BuildingConstr2 = 23,
	DodgeEnemy = 24,
	DecorativeBench = 25,
	DecorativeCrane = 26,
	DecorativeVoltageWires = 27,
	DecorativeWoodShield = 28
}
